
# name
name: hello world

# trigger
on:
- push

# one or more jobs
jobs:
    greetings:
        runs-on: ubuntu-latest
        steps:
            - id: s00
              run: echo "Current time in github is $(date)"
