
# name
name: hello world

# trigger
on:
- push

# one or more jobs
jobs:
    greetings:
        runs-on: ubuntu-latest
        steps:
            # A step is also called context in GH Actions
            - id: s00
              # running some shell bash command
              run: echo "Current time in github is $(date), ${GITHUB_OUTPUT}"
            - id: s01
              # Redirect in linux shell
              # Create a value and pass onto the next step
              run: echo "CURR_DATE=$(date)" >> $GITHUB_OUTPUT
            - id: s02
              uses: mscoutermarsh/cowsays-action@master
              with:
                text: 'HA ${{ steps.s01.outputs.CURR_DATE }}!'
                color: 'green'
            - id: s03
              uses: mscoutermarsh/cowsays-action@master
              with:
                text: 'I AM BLUE!'
                color: 'blue'
            #   run: ls -al
            # - id: s01
            #   run: cat README.md